// Generated by CoffeeScript 1.9.3
(function() {
  var assert;

  assert = require("assert");

  describe('Test', function() {
    var fm;
    fm = require('./../lib/index');
    return it('#Test', function() {
      fm;
      return assert.deepEqual(test, _t);
    });
  });

}).call(this);
