// Generated by CoffeeScript 1.9.3
(function() {
  var coordinates_index, from, get_in, latitude_index;

  get_in = function(obj, path) {
    var i, len, t, x;
    t = obj;
    for (i = 0, len = path.length; i < len; i++) {
      x = path[i];
      if (!t) {
        return null;
      }
      if (_isFn(x)) {
        t = t.filter(x)[0];
      } else {
        t = t[x];
      }
    }
    return t;
  };

  coordinates_index = function(d) {
    var k;
    k = "http://zdrav.spb.ru";
    return get_in(d, [
      'extension', (function(x) {
        return get_in(x, ['url']) === k;
      })
    ]);
  };

  latitude_index = function(d, k) {
    return get_in(d, [
      (function(x) {
        return get_in(x, ['url']) === k;
      })
    ]);
  };

  from = function(o, m) {
    var k, res, v;
    res = {};
    for (k in o) {
      v = o[k];
      switch (k) {
        case 'extension':
          res.coordinates = v[0];
          res = coordinates_index(v);
      }
    }
    return res;
  };

  module.exports = {
    from: from
  };

}).call(this);
