// Generated by CoffeeScript 1.9.3
(function() {
  var fromModel;

  fromModel = function(o, m) {
    return {
      foo: 5,
      bar: 'baz'
    };
  };

  module.exports = {
    fromModel: fromModel
  };

}).call(this);
